### ISSUE TITLE
Spacing Hauptbereich

### ISSUE THREAD

**Issue by Niffi** [BountyApplication/BountyApplication#25]
### Gewünschtes Aussehen:
Das Abstand zwischen Seitenleiste und Hauptbereich sollte rechts genauso groß sein wie auf der Links Seite zum Rand der Website.

Aktueller Stand:
![grafik](https://user-images.githubusercontent.com/10351860/171997404-9fa7a9db-b958-43ba-a062-3e4dc0434dc1.png)

Design Vorschlag:
![grafik](https://user-images.githubusercontent.com/10351860/171997406-d4d537b8-12c1-4dd3-9f7b-948617bdd1ec.png)

**Comment by IsiTapier** [comment]
Bei mir sieht es schon so aus
![grafik](https://user-images.githubusercontent.com/41296026/174564402-cbe14e9d-1447-4c0f-9d6c-0b086eed56ed.png)
