### ISSUE TITLE
Design Idee Verlauf

### ISSUE THREAD

**Issue by IsiTapier** [BountyApplication/BountyApplication#32]

**Comment by Niffi** [comment]
@IsiTapier: was hälst du davon? wenn dir das zusagt arbeite ich da noch etwas weiter dran. 
wenn nicht mache ich einen neuen vorschlag. 

<img width="800" alt="grafik" src="https://user-images.githubusercontent.com/10351860/175782865-026ba411-6435-4620-a5e7-534e89a32119.png">
