### ISSUE TITLE
Esc Taste im User Search modal 

### ISSUE THREAD

**Issue by Niffi** [BountyApplication/BountyApplication#33]
## Aktuelles Verhalten
Wenn ich im User Search bin und Esc drücke schließt sich direkt das ganze Modal. 

## Gewünschtes Verhalten
Ich denke es wäre besser wenn die Esc taste schrittweise vorgeht. 

Schritt 1: Den "Zurücksetzen" button triggern  
Schritt 2:  Modal schliessen

**Comment by IsiTapier** [comment]
Wie wärs mit esc zum schließen und entf für löschen?
