### ISSUE TITLE
Inaktiver User über Code aufrufbar

### ISSUE THREAD

**Issue by Niffi** [BountyApplication/BountyApplication#43]
### Beschreibung
Über den Code können Userkonten von Inativen Usern aufgerufen werden.

### Ziel
Inaktive Konten sollten sowohl über den Namen als auch über den Code nicht mehr aufrufbar sein. 

### Beweis

![grafik](https://user-images.githubusercontent.com/10351860/180031377-6a6edc72-515e-4115-a305-f18193e17f84.png)
![grafik](https://user-images.githubusercontent.com/10351860/180031543-455885cb-334d-440d-9b41-0d721eb1caff.png)

**Comment by IsiTapier** [comment]
Gut dass du das gleich testest, wär da net drauf gekommen xD
