### ISSUE TITLE
Buchen button ausgrauen

### ISSUE THREAD

**Issue by Niffi** [BountyApplication/BountyApplication#8]
### Gewünschtes verhalten:

Der Buchen button soll bei nicht genug guthaben ausgegraut werden. so dass eine buchung kein negatives guthaben auslösen kann.

**Comment by DerMatzee** [comment]
hggh

**Comment by DerMatzee** [comment]
Könnten die ausgegrauten Felder entweder stärker ausgegraut sein?
Also das nicht nur der Rahmen grau ist, sondern die ganze Fläche?

Bzw alle möglichen Felder als blau darstellen und dann das jetzige "ausgrauen" so lassen.

**Comment by Niffi** [comment]
Hey Matze, 
der Button im Bereich "Buchen" ist bereit stärker ausgegraut. Dieser Fall tritt allerdings nur selten auf, da ein negatives guthaben im Einkaufskorb nicht über die Produkte erzeugt werden kann. Das ist nur möglich wenn mann versucht Guthaben aus zu zahlen welches nicht vorhanden ist oder wenn man versucht eine Korrektur zu buchen welche ein negatives Guthaben zur folge hätte. Siehe screenshots :)

## Look bei ausreichend Guthaben:
![grafik](https://user-images.githubusercontent.com/10351860/174860313-a04384fb-1ddd-4e07-a416-01aa6ecd0e7c.png)

## Look bei nicht ausreichend Guthaben:
![grafik](https://user-images.githubusercontent.com/10351860/174860606-7a7cad47-f465-4913-b56b-2c441b10dbdd.png)
